# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalancoHidrico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diurese', models.BooleanField()),
                ('evac', models.BooleanField()),
                ('dreno_d', models.BooleanField()),
                ('dreno_e', models.BooleanField()),
                ('portovack', models.BooleanField()),
                ('outros', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ControleEspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avp', models.CharField(max_length=20)),
                ('clp', models.CharField(max_length=20)),
                ('avc', models.CharField(max_length=20)),
                ('cdl', models.CharField(max_length=20)),
                ('colocado_dia', models.DateField(blank=True)),
                ('trocar_dia', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npt', models.BooleanField()),
                ('ne', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.IntegerField(choices=[(1, 'F'), (2, 'M')])),
                ('endereco', models.CharField(blank=True, max_length=250, null=True)),
                ('telefone', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SinalVital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinatura', models.CharField(max_length=20)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('pa', models.BooleanField()),
                ('t', models.BooleanField()),
                ('p', models.BooleanField()),
                ('r', models.BooleanField()),
                ('eva', models.BooleanField()),
                ('spo2', models.BooleanField()),
                ('dextro', models.BooleanField()),
            ],
        ),
    ]
