# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ala', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Leito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_leito', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='PrescricaoEnfermagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('ala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescricao_enfermagem.Ala')),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescricao_enfermagem.Especialidade')),
                ('leito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescricao_enfermagem.Leito')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
            ],
        ),
    ]
